### PR TITLE
Improve lookup with full url, and filter.

### PR DESCRIPTION
**Pull request by Carreau**
```
$ python -m intersphinx_registry.lookup numpy,scipy Universal
std:label ufuncs                             NumPy 2.1    'Universal functions (ufunc)'                         https://numpy.org/doc/stable/reference/ufuncs.html#ufuncs
std:label ufuncs-basics                      NumPy 2.1    'Universal functions (ufunc) basics'                  https://numpy.org/doc/stable/user/basics.ufuncs.html#ufuncs-basics
std:label ufuncs-internals                   NumPy 2.1    'Universal functions'                                 https://numpy.org/doc/stable/dev/internals.code-explanations.html#ufuncs-internals
std:doc   reference/ufuncs                   NumPy 2.1    'Universal functions (ufunc)'                         https://numpy.org/doc/stable/reference/ufuncs.html
std:doc   user/basics.ufuncs                 NumPy 2.1    'Universal functions (ufunc) basics'                  https://numpy.org/doc/stable/user/basics.ufuncs.html
std:label non-uniform-random-number-sampling SciPy 1.14.1 'Universal Non-Uniform Random Number Sampling in SciPy' https://docs.scipy.org/doc/scipy/tutorial/stats/sampling.html#non-uniform-random-number-sampling
std:doc   tutorial/stats/sampling            SciPy 1.14.1 'Universal Non-Uniform Random Number Sampling in SciPy' https://docs.scipy.org/doc/scipy/tutorial/stats/sampling.html
```

### CODE REVIEW

**Comment by Carreau** [comment]
@matthewfeickert I believe you were the one using lookup right ?

**Comment by matthewfeickert** [comment]
> I believe you were the one using lookup right ?

I don't think so(?), as the default project we would have been discussion [doesn't show it](https://github.com/scikit-hep/pyhf/blob/1f1adc7d07883c04511defbbbeb0e5c7f4e11722/docs/conf.py#L83-L91). But maybe this was another discussion/project and I forgot?

**Comment by Carreau** [comment]
Yeah, I don't remember, it was in the big room at the e-science institut, and someone told me "hey it would be great with intersphinx lookup", and I thought it was you. 


Anyway, if you are interested in using intersphinx-registry for scikit-hep, I can send a PR.

**Comment by matthewfeickert** [comment]
> Anyway, if you are interested in using intersphinx-registry for scikit-hep, I can send a PR.

That would be amazing. Even an email to me reminding me what is needed would be great. Thanks! :)

**Pull request merged**
